name: Release
on:
  release:
    types:
      - created
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-18.04
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: build and push to remote registry
        env:
          TAG:   ${{ env.GITHUB_REF_SLUG }}
        run: |
          echo ${{secrets.REPO_KEY}} | docker login --username ${{secrets.REPO_USER}} --password-stdin
          make release-push

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ui-web-amd64.zip
            ui-web-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
